### ISSUE TITLE
Add compatibility with django 5.0

### ISSUE THREAD

**Issue by DeeeeLAN** [reganto/django-ptpython#5]
**Environment**
django-ptpython version: v1.0.2
django version: v5.0.6
python version: v3.12.3
pip version: v24.0
os: python:3.12.3-bookworm

**Describe the bug**
Attempting to install the listed versions above shows a dependency error, stating django-ptpython requires `django<4.0.0,>=3.2.14`.

**Comment by DeeeeLAN** [comment]
Installing v1.0.1 allows `django<5.0,>=4.0`, which still doesn't help.

**Comment by reganto** [comment]
#6
